---
title: "Week 4: Simulating Subjects, Interactive Agents, and Survey Experiments"
subtitle: "AI for Social Science Research"
format:
  revealjs:
    theme: default
    link-external-newwindow: true
    slide-number: true
    transition: fade
    width: 1600
    height: 900
---

## Plan of Today & Logistics
::: {style="font-size: 0.9em;"}
- **[Student Presentation](https://docs.google.com/presentation/d/15rOD2gZB4qTOd4y4zv_gzRRg5JqQT50n/edit?slide=id.p1#slide=id.p1) & Discussion** ~60 min, clarifying questions & critical evaluation of readings
- **Break** 10 min
- **Lab** ~45 min, simulating survey subjects (sillicon sampling), tailored experiment tools, simulating agents (demo only)
- **Course project co-work** ~45 min, talk to me for any questions
:::
. . .

::: {style="font-size: 0.9em;"}
- Two new learning resources added to the [syllabus](https://di-zhou.github.io/ai_for_socsci_fall2026/syllabus.html#learning-resources) online:
  - [Rutgers IT: Research Computing Events](https://it.rutgers.edu/research-computing/events/list/) - workshops and events on data science, AI, and HPC resources.
  - [Rutgers Newark Institute for Data, Research and Innovation Science, Large Language Reading/Retooling (LLRs) Series](https://idris.rutgers.edu/events/) -workshops and events on AI & LLMs.
:::

. . .

::: {style="font-size: 0.9em;"}
Next week: 

- Reading presentation (9/30): AutoResearch, by Chun-Ching, Duhui, and Yujia
- Make sure you have either **Claude Pro** or **ChatGPT Plus** set up for next week's class!
:::